[project]
name = "repl-nix-workspace"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "chromadb>=1.1.1",
    "discord-py>=2.6.4",
    "langchain>=0.3.27",
    "langchain-community>=0.3.31",
    "langchain-openai>=0.3.35",
    "openai>=2.3.0",
    "python-dotenv>=1.1.1",
    "tiktoken>=0.12.0",
]
